/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.5
 * Generated at: 2018-09-04 08:03:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>EVENT</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css.css\">\r\n");
      out.write("<style>\r\n");
      out.write("@font-face{\r\n");
      out.write("\tfont-family: 'Calligraphy Personal Use'; src:url('font/Calligraphy Personal Use.ttf');\r\n");
      out.write("}\r\n");
      out.write("@font-face{font-family:'NANUMSQUAREROUNDL'; src:url('font/NANUMSQUAREROUNDL.TTF')}\r\n");
      out.write("@font-face{font-family:'NANUMSQUAREROUNDB'; src:url('font/NANUMSQUAREROUNDB.TTF')}\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("\tmargin:0px;\r\n");
      out.write("\tpadding:0px;\r\n");
      out.write("\tfont-family:'NANUMSQUAREROUNDL';\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div style = \"background-color: #151515; width: 100%; height: 800px; padding-top:5%;\">\r\n");
      out.write("\t<div style = \"font-size: 20pt; color:red; text-align: center;\"><font style = \"font-family: NANUMSQUAREROUNDB\"><당신도 탐정이 될 수 있다 EVENT></font></div>\r\n");
      out.write("\t<div style = \"color:white; text-align: center;\"><font style=\"font-family: Calligraphy Personal Use; font-size: 15em;\">You can be a detective</font></div>\r\n");
      out.write("\t\t<div style = \"font-size: 15pt; color:white; margin-left:20%\"><font style = \"font-family: NANUMSQUAREROUNDL\">추리 소설 탄생 <font color=\"red\">177주년</font> 기념</font></div>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t<div style = \"font-size:18pt; color:white;  margin-left:28%; font-family:NANUMSQUAREROUNDB \">퀴즈를 풀고 히가시노 게이고 & 애거사 크리스티 & 아서 코난 도일 소설책을 받아가세요!</div>\r\n");
      out.write("\t<div style = \"font-size:18pt; color:white;  margin-left:38%; font-family:NANUMSQUAREROUNDB \">선착순 20명에게 랜덤으로 책을 선물해 드립니다</div>\r\n");
      out.write("\t<div class=\"buttonContainer\">\r\n");
      out.write(" <a class=\"button\" onclick=\"showPopup();\" title=\"quiz\">퀴즈 풀고 소설책 받으러 가기</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style = \"text-align: center; margin-top:5%; color:black; font-weight: 900\"><h2>세계인이 좋아한 추리 소설 </h2></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 여기서부터 책 정보 -->\r\n");
      out.write("<div class=\"component\">\r\n");
      out.write("  <ul class=\"align\">\r\n");
      out.write("    <!-- Book 1 -->\r\n");
      out.write("    <li style = \"margin-left:2%\">\r\n");
      out.write("      <figure class='book'>        \r\n");
      out.write("        <!-- Front -->        \r\n");
      out.write("        <ul class='hardcover_front'>\r\n");
      out.write("          <li>\r\n");
      out.write("            <img src=\"http://mblogthumb1.phinf.naver.net/MjAxODAzMTlfMTk5/MDAxNTIxNDQ3NzQ3NjM2.WZShtX_uO_6JNCjy4xDTl9yvU6wH8278slTFLA-zaUcg.0Mm19c-3gQU2v65n9_Ye-rjnCH5XyFbuNSzHMRZffIwg.JPEG.hla9865/1452422-flyjoy77.jpg?type=w800\" alt=\"\" width=\"100%\" height=\"100%\">\r\n");
      out.write("            <span class=\"ribbon bestseller\"></span>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>        \r\n");
      out.write("        <!-- Pages -->        \r\n");
      out.write("        <ul class='page'>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a class=\"btn\" href=\"#\">DETAIL</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>        \r\n");
      out.write("        <!-- Back -->        \r\n");
      out.write("        <ul class='hardcover_back'>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class='book_spine'>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <figcaption>\r\n");
      out.write("          <h2>용의자 X의 헌신</h2>\r\n");
      out.write("          <span style = \"color:red\">히가시노 게이고</span>\r\n");
      out.write("          <p>평범한 수학교사인 이시가미는 옆집의 야스코를 짝사랑한다. 그녀가 전 남편에 시달린 나머지 그녀의 딸과 공조하여 남편을 죽였다는 사실을 알아차린 이시가미는 그녀의 범행사실을 은폐하는 것을 도와준다. 이시가미의 계획은 결점없어 보였지만 그의 예전 동창이자 호적수인 천재 물리학자 유가와에게 약점을 노출하게 되는데...</p>\r\n");
      out.write("        </figcaption>\r\n");
      out.write("      </figure>\r\n");
      out.write("    </li>  \r\n");
      out.write("    \r\n");
      out.write("     <li style = \"margin-left:2%\">\r\n");
      out.write("      <figure class='book'>        \r\n");
      out.write("        <!-- Front -->        \r\n");
      out.write("        <ul class='hardcover_front'>\r\n");
      out.write("          <li>\r\n");
      out.write("            <img src=\"https://t1.daumcdn.net/thumb/R1280x0/?fname=http://t1.daumcdn.net/brunch/service/user/7ur/image/jF5nkBVAa_RBbcVq0lpbcK3Nfvc.jpg\" alt=\"\" width=\"100%\" height=\"100%\">\r\n");
      out.write("            <span class=\"ribbon bestseller\"></span>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>        \r\n");
      out.write("        <!-- Pages -->        \r\n");
      out.write("        <ul class='page'>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a class=\"btn\" href=\"#\">DETAIL</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>        \r\n");
      out.write("        <!-- Back -->        \r\n");
      out.write("        <ul class='hardcover_back'>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class='book_spine'>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <figcaption>\r\n");
      out.write("          <h2>라플라스의 마녀</p></h2>\r\n");
      out.write("          <span style = \"color:red\">히가시노 게이고</span>\r\n");
      out.write("          <p>외갓집에 갔다가 갑작스런 토네이도에 휩쓸려 엄마를 잃은 소녀, 마도카. 그로부터 8년 후 한 지방의 온천지에서 '황화수소 가스 중독'으로 인해 60대의 영화 프로듀서가 사망하는 사건이 발생한다. 그러나 그 후, 또 한 건의 사건이 발생한다. 앞서 발생한 사고와 같은 사건이었다. 자문을 위해 찾은 두 번째 사건 장소에서 아오에  교수는 한 소녀를 발견하는데 두 사건 현장에 나타난 그 소녀는 마도카였다..</p>\r\n");
      out.write("        </figcaption>\r\n");
      out.write("      </figure>\r\n");
      out.write("    </li>  \r\n");
      out.write("    \r\n");
      out.write("    <!-- Book 2 -->\r\n");
      out.write("    <li>\r\n");
      out.write("      <figure class='book'>        \r\n");
      out.write("        <!-- Front -->        \r\n");
      out.write("        <ul class='hardcover_front'>\r\n");
      out.write("          <li>\r\n");
      out.write("            <img src=\"https://misc.ridibooks.com/cover/1153000080/xxlarge\" alt=\"\" width=\"100%\" height=\"100%\">\r\n");
      out.write("            <span class=\"ribbon new\">NEW</span>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>        \r\n");
      out.write("        <!-- Pages -->        \r\n");
      out.write("        <ul class='page'>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li>\r\n");
      out.write("             <a class=\"btn\" href=\"#\">DETAIL</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>        \r\n");
      out.write("        <!-- Back -->        \r\n");
      out.write("        <ul class='hardcover_back'>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class='book_spine'>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <figcaption>\r\n");
      out.write("          <h2>셜록 홈즈 전집</h2>\r\n");
      out.write("          <span style = \"color:red\">아서 코난 도일</span>\r\n");
      out.write("          <p>코난 도일이 저술한 셜록 홈즈를 주인공으로 하는 영국의 추리 소설 시리즈. 추리 소설이란 장르를 대중들에게 소개한 작품 중 하나이며 영국에서 출발한 추리 소설 황금기의 시초 겸 대표작이라 할 만하다. 셜록 홈즈 시리즈는 장편으로 주홍색 연구, 네 개의 서명, 바스커빌 가의 개, 공포의 계곡으로 이루어져 있으며 단편으로 셜록 홈즈의 모험, 회상록, 귀환,  마지막 인사, 사건집이 있다.</p>\r\n");
      out.write("        </figcaption>\r\n");
      out.write("      </figure>\r\n");
      out.write("    </li>  \r\n");
      out.write("    <!-- Book 3 -->\r\n");
      out.write("    <li>\r\n");
      out.write("      <figure class='book'>       \r\n");
      out.write("        <!-- Front -->        \r\n");
      out.write("        <ul class='hardcover_front'>\r\n");
      out.write("          <li>\r\n");
      out.write("            <img src=\"https://misc.ridibooks.com/cover/682000192/xxlarge\" alt=\"\" width=\"100%\" height=\"100%\">\r\n");
      out.write("          </li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>        \r\n");
      out.write("        <!-- Pages -->        \r\n");
      out.write("        <ul class='page'>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a class=\"btn\" href=\"#\">DETAIL</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>        \r\n");
      out.write("        <!-- Back -->        \r\n");
      out.write("        <ul class='hardcover_back'>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class='book_spine'>\r\n");
      out.write("          <li></li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <figcaption>\r\n");
      out.write("          <h2>애거서 크리스티:<br>그리고 아무도 없었다</h2>\r\n");
      out.write("          <span style = \"color:red\">애거서 크리스티</span>\r\n");
      out.write("          <p>지역 주민들이 '인디언 섬(니거 섬)'이라고 부르는 작은 섬에 8명의 남녀가 초대된다. '얼릭 노먼 오언'이란 의문의 사람에게 초대받아 온 일행 앞에 정작 주인인 얼릭 노먼 오언과 그 부인인 '유나 낸시 오언'은 없고 하인 부부만이 그들을 맞이하는데... 그리고 이 지방에 내려오는 인디언 인형 노래에 맞춰서 끔찍한 참극이 벌어진다. </p>\r\n");
      out.write("        </figcaption>\r\n");
      out.write("      </figure>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>  \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write(" <script language=\"javascript\">\r\n");
      out.write("  function showPopup() { window.open(\"quiz.jsp\", \"a\", \"width=750px, height=850px, left=100, top=50\"); }\r\n");
      out.write("  </script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
