/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.5
 * Generated at: 2018-09-04 22:43:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class quiz_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>EVENT</title>\r\n");
      out.write("<style>\r\n");
      out.write("@font-face{\r\n");
      out.write("\tfont-family: 'Calligraphy Personal Use'; src:url('font/Calligraphy Personal Use.ttf');\r\n");
      out.write("}\r\n");
      out.write("@font-face{font-family:'NANUMSQUAREROUNDL'; src:url('font/NANUMSQUAREROUNDL.TTF')}\r\n");
      out.write("@font-face{font-family:'NANUMSQUAREROUNDB'; src:url('font/NANUMSQUAREROUNDB.TTF')}\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("\tmargin:7%;\r\n");
      out.write("\tpadding:0px;\r\n");
      out.write("\tfont-family:'NANUMSQUAREROUNDB';\r\n");
      out.write("\tbackground-color: #151515;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button{\r\n");
      out.write("  background:red;\r\n");
      out.write("  color:#fff;\r\n");
      out.write("  border:none;\r\n");
      out.write("  position:relative;\r\n");
      out.write("  height:60px;\r\n");
      out.write("  font-size:1em;\r\n");
      out.write("  padding:0 2em;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("  transition:800ms ease all;\r\n");
      out.write("  outline:none;\r\n");
      out.write("}\r\n");
      out.write("button:hover{\r\n");
      out.write("  background:#151515;\r\n");
      out.write("  color:white;\r\n");
      out.write("}\r\n");
      out.write("button:before,button:after{\r\n");
      out.write("  content:'';\r\n");
      out.write("  position:absolute;\r\n");
      out.write("  top:0;\r\n");
      out.write("  right:0;\r\n");
      out.write("  height:2px;\r\n");
      out.write("  width:0;\r\n");
      out.write("  background: red;\r\n");
      out.write("  transition:400ms ease all;\r\n");
      out.write("}\r\n");
      out.write("button:after{\r\n");
      out.write("  right:inherit;\r\n");
      out.write("  top:inherit;\r\n");
      out.write("  left:0;\r\n");
      out.write("  bottom:0;\r\n");
      out.write("}\r\n");
      out.write("button:hover:before,button:hover:after{\r\n");
      out.write("  width:100%;\r\n");
      out.write("  transition:800ms ease all;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<form action = \"quiz_result.jsp\" method=\"post\" name = \"Myform\">\r\n");
      out.write("<center><div style = \"font-family: Calligraphy Personal Use; font-size: 90pt; margin-top:5%\">Detective test</div></center>\r\n");
      out.write("\r\n");
      out.write("<center><h1 style = \"color:red\">당신도 탐정이 될 수 있다 EVENT1</h1>\r\n");
      out.write("<div style = \"color: white;\">아래의 두 개의 문제를 푼 후 정답을 맞추면 내 손안에 추리소설 책이! <br>\r\n");
      out.write("더 어려운 문제를 풀고 탐정임명장을 얻어보세요!</div>\r\n");
      out.write("<br><br>\r\n");
      out.write("<hr color=\"red\" style = \"width: 50%\">\r\n");
      out.write("<br>\r\n");
      out.write("<div style = \"font-size: 20pt;\">첫번째 문제</div>\r\n");
      out.write("<br>\r\n");
      out.write("<hr color=\"red\" style = \"width: 50%\">\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("</center>\r\n");
      out.write("<center>\r\n");
      out.write("A와 B는 스페인의 시골마을을 여행하고 있었다. <br><br>\r\n");
      out.write("어젯밤 타파스 바에서 신나게 먹고 마시느라 <br><br> 둘 다 배터리 충전을 깜빡해 \r\n");
      out.write("휴대전화는 꺼졌고 지도마저 잃어버렸는데, 갈림길을 만났다.<br><br>\r\n");
      out.write("목적지인 산티아고로 가려면 왼쪽, 오른쪽 어느 쪽으로 가야 할지 난감한 상황. <br><br>\r\n");
      out.write("다행이 갈림길 앞 벤치에 노인 두명이 나란히 앉아 있다. <br><br>길을 물어으려 다가가니<br><br> </center>\r\n");
      out.write("<div style = \"margin-left:15%;\"><img src =\"img/quote-left.png\" widt=40px height=40px>&nbsp;&nbsp;\r\n");
      out.write("두 노인 중 한명은 참말만, 다른 한명은 거짓말만 한다.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;질문은 한명에게 딱 한번만 할 수 있다.<br><img src =\"img/right-quote-sign.png\" widt=40px height=40px style = \"margin-left:60%;\"></div><br>\r\n");
      out.write("는 팻말이 벤치에 붙어 있다. A와 B는 누구에게 어떤 질문을 해야 맞는 길로 갈 수 있을까?<br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<label><input type = \"radio\" name = \"quiz1\" value = \"1\" style=\"width:20px;height:20px;\"> 왼쪽 노인에게 \"왼쪽 길이 산티아고 가는 길인가요?\"</label><br><br>\r\n");
      out.write("\t<label><input type = \"radio\" name = \"quiz1\" value = \"2\" style=\"width:20px;height:20px;\"> 오른쪽 노인에게 \"오른쪽 길이 산티아고 가는 길인가요?\"</label><br><br>\r\n");
      out.write("\t<label><input type = \"radio\" name = \"quiz1\" value = \"3\" style=\"width:20px;height:20px;\"> 아무에게나 \"산티아고 가는 길이 어느 쪽인가요?\"</label><br><br>\r\n");
      out.write("\t<label><input type = \"radio\" name = \"quiz1\" value = \"4\" style=\"width:20px;height:20px;\"> 아무에게나 \"옆에 계신 분께 산티아고 가는 길을 물으면 어느 쪽이라고 답하실까요?\"</label><br><br>\r\n");
      out.write("\t\r\n");
      out.write("<center>\r\n");
      out.write("<br><br>\r\n");
      out.write("<hr color=\"red\" style = \"width: 50%; \">\r\n");
      out.write("<br>\r\n");
      out.write("<div style = \"font-size: 20pt;\">두번째 문제</div>\r\n");
      out.write("<br>\r\n");
      out.write("<hr color=\"red\" style = \"width: 50%;\">\r\n");
      out.write("<br>\r\n");
      out.write("<br>\t\r\n");
      out.write("한 회사의 간부인 P씨가 회사 내에서 살해당한 채 발견되었다.<br><br>\r\n");
      out.write("P씨의 컴퓨터에는<br><br>\r\n");
      out.write(" <div style=\"border:1px solid; padding:10px; font-size: 20pt\"> 741231475369 </div><br><br>\r\n");
      out.write(" 라는 의문의 메세지가 남아있었다.<br><br>\r\n");
      out.write(" 다음 용의자 중 범인은 누구일까? <br><br>\r\n");
      out.write(" </center>\t\t\r\n");
      out.write("\t<label><input type = \"radio\" name = \"quiz2\" value = \"1\" style=\"width:20px;height:20px;\"> Jonny Black(52세, 남 / 엔지니어)이유 없는 인사이동에 불만을 품음</label><br><br>\r\n");
      out.write("\t<label><input type = \"radio\" name = \"quiz2\" value = \"2\" style=\"width:20px;height:20px;\"> Lenny Nilson(30세, 남 / 운전기사)P씨의 잦은 폭언에 최근 사직서 제출</label><br><br>\r\n");
      out.write("\t<label><input type = \"radio\" name = \"quiz2\" value = \"3\" style=\"width:20px;height:20px;\"> Alison Ruby(23세, 여 / 비서)P씨의 무례한 행동에 수치심을 느낌</label><br><br>\r\n");
      out.write("\t<label><input type = \"radio\" name = \"quiz2\" value = \"4\" style=\"width:20px;height:20px;\"> Sheldon Wanda(41세, 여 / 청소부)임금문제로 1인 시위 중</label><br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<button type = \"button\" name = \"button\" style = \"margin-left: 40%; margin-top:10%\" onClick=\"javascript:onSubmit();\">제출하기</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction onSubmit(){\r\n");
      out.write("\t\tvar robj = document.getElementsByName(\"quiz1\");\r\n");
      out.write("\t\tvar robj2 = document.getElementsByName(\"quiz2\");\r\n");
      out.write("\t\tvar checknum1 = 0;\r\n");
      out.write("\t\tvar checknum2 = 0;\r\n");
      out.write("\t\tvar form = document.Myform;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(var i = 0; i <robj.length; i++){\r\n");
      out.write("\t\t\tif(robj[i].checked == true) checknum1++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(var i = 0; i <robj2.length; i++){\r\n");
      out.write("\t\t\tif(robj2[i].checked == true) checknum2++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(checknum1 < 1 || checknum2 < 1){\r\n");
      out.write("\t\t\talert(\"풀지 않은 문제가 있습니다!\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tform.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
